apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.portNodePortRequest}}
      {{- end }}
      name: request
    - port: {{ .Values.service.portEvent }}
      targetPort: 7053
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.portNodePortEvent}}
      {{- end }}
      name: event
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
